### PR TITLE
feat: Implements i32.xor

### PR DESCRIPTION
**Pull request by ColinEberhardt**
I wanted to start with a very small contribution, similar to #43 - just to make sure I'm following the process / conventions.

If this commit is OK, I'd be happy to look at binary operations in general, and how to handle the common functions between these instructions.

relates to #1

### CODE REVIEW

**Comment by xtuc** [comment]
Thanks for your contribution.

I restarted the build it seems that Travis failed to clone the repo (not related to your changes).

**Comment by maurobringolf** [comment]
Thats so cool! A general remark on implementing new instructions: I tried not too hard to cover all edge cases in the ones Ive done yet. I think wed do better if we get it 95% correct, merge and then iterate.

What do you guys think?
Again: not specific to this instruction or implementation.

**Comment by xtuc** [comment]
@maurobringolf yes, I agree! Since we planned to refactor i64 and numeric literals.

**Comment by ColinEberhardt** [comment]
Thanks @maurobringolf if this PR gets the thumbs up, I’ll go for something more substantial next, probably all binary ops. It’s probably easier to looks at edge cases (runtime validation and unit testing) at that point.

**Comment by maurobringolf** [comment]
@ColinEberhardt Perfect. I think at least with i32 you shouldn't run into edge cases since there are no special values and JS supports the full range of values.

**Pull request merged**
